"""Add image_url to Task model

Revision ID: d157259c8aac
Revises: c2f3a6c27f4f
Create Date: 2024-11-15 22:25:57.293146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd157259c8aac'
down_revision = 'c2f3a6c27f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
